[package]
name = "numbers-guy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
dotenvy = "0.15.7"
octocrab = "0.39.0"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["rt", "macros", "rt-multi-thread"] }
